apiVersion: v1
kind: LimitRange
metadata:
  name: httplimitrange
  namespace: gracehttp
spec:
  limits:
  - type: Pod
    min:
      cpu: 200m
      memory: 200Mi
    max:
      cpu: 2000m
      memory: 2048Mi
  - type: Container
    defaultRequest:
      cpu: 200m
      memory: 200Mi
    default:
      cpu: 400m
      memory: 400Mi
    min:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 1000m
      memory: 600Mi
    maxLimitRequestRatio:
      cpu: 5
      memory: 5


